[build]
builder = "nixpacks"
installCommand = "npm install"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/main"
healthcheckPath = "/api"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
